"""operations

Revision ID: 3ab0814292cd
Revises: 424c93c99ce1
Create Date: 2025-05-28 23:51:02.416641

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3ab0814292cd'
down_revision: Union[str, None] = '424c93c99ce1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'operations',
        'created_at',
        existing_type=sa.DATE(),
        type_=sa.DateTime(),
        existing_nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'operations',
        'created_at',
        existing_type=sa.DateTime(),
        type_=sa.DATE(),
        existing_nullable=False
    )
    # ### end Alembic commands ###
