"""cards

Revision ID: df46162d8635
Revises: bc7890aa2e54
Create Date: 2025-06-04 20:16:29.276439

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'df46162d8635'
down_revision: Union[str, None] = 'bc7890aa2e54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('card_number', sa.String(length=50), nullable=False))
    op.add_column('cards', sa.Column('card_holder', sa.String(length=250), nullable=False))
    op.add_column('cards', sa.Column('expiry_date', sa.Date(), nullable=False))
    op.add_column('cards', sa.Column('payment_system', sa.String(length=50), nullable=False))
    op.drop_column('cards', 'expired_at')
    op.drop_column('cards', 'number')
    op.drop_column('cards', 'cardholder')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('cardholder', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
    op.add_column('cards', sa.Column('number', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('cards', sa.Column('expired_at', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('cards', 'payment_system')
    op.drop_column('cards', 'expiry_date')
    op.drop_column('cards', 'card_holder')
    op.drop_column('cards', 'card_number')
    # ### end Alembic commands ###
