"""cards

Revision ID: fc090b022f82
Revises: 
Create Date: 2025-05-26 23:57:14.850680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'fc090b022f82'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'cards',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('pin', sa.Integer(), nullable=False),
        sa.Column('cvv', sa.Integer(), nullable=False),
        sa.Column('type', sa.String(length=50), nullable=False),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('number', sa.Integer(), nullable=False),
        sa.Column('expired_at', sa.Date(), nullable=False),
        sa.Column('cardholder', sa.String(length=100), nullable=False),
        sa.Column('account_id', sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cards')
    # ### end Alembic commands ###
